Update FSPath.cpp to #include <cstring>
Because of this message during build

hough@fedora-framework:~/src/FEBio-build$ make
[  0%] Building CXX object CMakeFiles/fecore.dir/FECore/FSPath.cpp.o
/home/mhough/src/FEBio/FECore/FSPath.cpp: In static member function ‘static void FSPath::filePath(char*, char*)’:
/home/mhough/src/FEBio/FECore/FSPath.cpp:54:9: error: ‘strcpy’ was not declared in this scope
   54 |         strcpy(path,"");
      |         ^~~~~~
/home/mhough/src/FEBio/FECore/FSPath.cpp:30:1: note: ‘strcpy’ is defined in header ‘<cstring>’; this is probably fixable by adding ‘#include <cstring>’
   29 | #include "FSPath.h"
  +++ |+#include <cstring>
   30 | 
make[2]: *** [CMakeFiles/fecore.dir/build.make:2372: CMakeFiles/fecore.dir/FECore/FSPath.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:258: CMakeFiles/fecore.dir/all] Error 2
make: *** [Makefile:91: all] Error 2